### ISSUE TITLE
not debugging mode cannot censor the checked key-frame

### ISSUE THREAD

**Issue by KandaTeach** [zvz23/vProfanity#1]
Try disabling the logs.

**Comment by zvz23** [comment]
Fixed [#a69656dfb04aed7f](https://github.com/zvz23/vProfanity/commit/a69656dfb04aed7ff7794e09e87c4301aa289ce5) by setting logger to None to write_videofile in censor.py

**Comment by zvz23** [comment]
Fixed [a69656dfb04aed7](https://github.com/zvz23/vProfanity/commit/a69656dfb04aed7ff7794e09e87c4301aa289ce5) by setting logger=None to write_videofile in censor.py

**Comment by KandaTeach** [comment]
Okay, thank you.
