### ISSUE TITLE
No detected speech regions returns exception

### ISSUE THREAD

**Issue by KandaTeach** [zvz23/vProfanity#3]
![image](https://user-images.githubusercontent.com/59522699/234363431-762abc41-803e-496d-b587-2c1b4766a044.png)

It returns an invalid cast exception when I try to scan the sexual-03 video from the testing dataset.

**Comment by zvz23** [comment]
Fixed [bee2c39cc3c421](https://github.com/zvz23/vProfanity/commit/bee2c39cc3c4214babb9d83533b97eddd4a30e0a) by returning an empty list instead of None
