### ISSUE TITLE
Extract sexual key-frames is not yet included.

### ISSUE THREAD

**Issue by KandaTeach** [zvz23/vProfanity#7]
![image](https://user-images.githubusercontent.com/59522699/234763785-8c9eac5e-d020-49ba-9ea5-7866b11a9a1c.png)

I already selected a sexual key-frame but still it doesn't extract.

**Comment by zvz23** [comment]
The feature only works on selecting a word segment

**Comment by KandaTeach** [comment]
Yeah I remember now the feature only works on selecting word segment, sorry about that.

Closing this issue due to confusion.
